on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Run actionlint and shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.11.0
        with:
          repo: pulumi/pulumictl
      - name: Install actionlint
        uses: jaxxstorm/action-install-gh-release@v1.11.0
        with:
          repo: rhysd/actionlint
      - name: lint native providers
        run: cd native-provider-ci && make lint
      - name: lint workflows
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
  test:
    name: Verify against testdata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.11.0
        with:
          repo: pulumi/pulumictl
      - name: Validate native-providers
        run: cd native-provider-ci && make all
      - name: Check worktree clean
        uses: pulumi/git-status-check-action@v1
  verify:
    name: Verify patches can be applied
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - run: make apply_patches
      - run: make reset
      - name: Check worktree clean
        uses: pulumi/git-status-check-action@v1
